services:
  pffdtd:
    build:
      context: .
      args:
        PFFDTD_REPO: "https://github.com/mskarha/pffdtd-dev"
        CUDA_ARCH: "sm_89"
    gpus: all
    tty: true
    stdin_open: true
    volumes:
      - pffdtd-work:/work
      - /home/matt/dev/pffdtd-dev:/src/pffdtd
      - /mnt/c/pffdtd-host-data:/host-data
volumes:
  pffdtd-work:
